### ISSUE TITLE
Visual connection of nodes

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#10]
After importing a file where a composite signal was added, lines between basic signals and composite one are missing. It could be misleading for users.
![image](https://user-images.githubusercontent.com/60115817/114981080-16d0d580-9e96-11eb-9fbe-508e5367c3c3.png)

**Comment by andreasxp** [comment]
Sorry for a late fix, composite signals will now be connected to derived signals whose name is in the expression.
Unfortunately this is not a perfect fix, since if you have signals `Signal` and `Signal1`, and an expression `Composite = Signal1`, both derived signal names will be found in the text and both will be connected. To implement a more robust check we need to find some kind of math expression library, which can identify variables in an expression.

Speaking of which, some kind of expression builder is also needed for the composite signal export UI to create syntactically correct expressions, and only with the signals that are allowed (connected). So I will keep this issue open until a proper fix is implemented.

**Comment by andreasxp** [comment]
Expression parsing has been implemented. I'll open a separate issue for the UI changes.
